### ISSUE TITLE
Treatment Panel

### ISSUE THREAD

**Issue by azev77** [nilshg/SynthControl.jl#16]
currently, units (id_var) have to be string: 
```julia
TreatmentPanel("United Kingdom" => Date(2016, 7, 1), df;
                       outcome = :realgdp, id_var = :country, t_var = :quarter)
```

It would be great to have numeric id_var etc

**Comment by nilshg** [comment]
This should work now with the new dependency on `TreatmentPanels` - any further feature requests related to this should be opened on the [TreatmentPanels](https://github.com/nilshg/TreatmentPanels.jl) repo, as I'm looking to separate problem definition from estimation algorithms.
